site_name: anki-insights
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API:
    - Tokenizers: api/tokenizers.md
    - Deduplicator: api/deduplicate.md
    - Inverter: api/invert.md
    - Reference: api_reference.md
  - Contributing: contributing.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            rendering:
              show_root_heading: true